### ISSUE TITLE
Fluxion 0.25

### ISSUE THREAD

**Issue by seventhplug** [deltaxflux/vimic#1]
Hello. I don't know how to contact you about fluxion. ^_^ its a great tool and it works flawlessly in my Raspberry Pi 3 with external dongle (TP-LINK WN722N) but i'm having issues when i try using it on Nethunter Devices (Nexus 2013 Flo) via OTG (TP-LINK WN722N).  During Selecting Interface. here's the error

./fluxion: line 795:  /dev/fd/62: No such file or Directory
Select an interface

[deltaxflux@fluxion]-[~]

my wifi dongle is detected and i can enable monitor mode via airmon. Thanks ^_^

**Comment by deltaxflux** [comment]
Kidding ?
